### ISSUE TITLE
CSS: landing page design

### ISSUE THREAD

**Issue by Bam92** [kaliacad/bible-tracker#11]
-[] no underline for book links
-[] book links color #000
-[] book card width: 50%

**Comment by bienvenu07** [comment]
Bonjour Monsieur Abel, 

 Je trouve le sujet  lieu à la conception de la page d'accueil 11 dollars  (  CSS: landing page design #11 ) mes va bien.

cordialement.

**Comment by bienvenu07** [comment]
Bonjour , 

je voulais comprendre à quoi consiste la carte-livre (book card ) 
 pour avancer

Cordialement.

**Comment by Bam92** [comment]
@bienvenu07,
Il s'agit de livres de la Bible comme tu peux le voir à la page d'accueil.
